spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/assignment-db?useSSL=false
    username: ejm
    password: ejm1234


  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # DB Dialect(??) ??
