spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/assignment_db?useSSL=false
    username: ${db-user}
    password: ${db-password}


  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # DB Dialect(??) ??
